# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2ab4e6bf6c3b9df65eb3358cc4b9fc65aae9e78203001725e047f5af3ed332f099bd931dc067cd0c147e18c85281609a74b930ac1f0e0dad4bcf3a937a4d3e9

test:
  secret_key_base: 38333d78ec6ee8789f2d905540174ba203292f4bab709e511ff1516d226e490d60f1cce9c9fbed8eeee9aecd66acc8dff083acebff0d8f442b9dd3db31693e17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
